# GNU Make project makefile autogenerated by Premake
ifndef config
  config=release64
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),release64)
  OBJDIR     = obj/x64/Release/App_BulletExampleBrowser
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/App_BulletExampleBrowser_gmake_x64_release
  DEFINES   += -DB3_USE_CLEW -DINCLUDE_CLOTH_DEMOS
  INCLUDES  += -I../../src/clew -I../../examples/ThirdPartyLibs/glad -I../../examples/ExampleBrowser -I../../src -I../../examples/SharedMemory -I../../examples/ThirdPartyLibs
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -msse2 -ffast-math -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -m64 -L/usr/lib64
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libBulletExampleBrowserLib_gmake_x64_release.a ../../bin/libgwen_gmake_x64_release.a ../../bin/libOpenGL_Window_gmake_x64_release.a ../../bin/libBulletSoftBody_gmake_x64_release.a ../../bin/libBulletInverseDynamicsUtils_gmake_x64_release.a ../../bin/libBulletInverseDynamics_gmake_x64_release.a ../../bin/libBulletDynamics_gmake_x64_release.a ../../bin/libBulletCollision_gmake_x64_release.a ../../bin/libLinearMath_gmake_x64_release.a ../../bin/libBussIK_gmake_x64_release.a ../../bin/libBullet3Common_gmake_x64_release.a ../../bin/libBullet3OpenCL_clew_gmake_x64_release.a ../../bin/libBullet3Dynamics_gmake_x64_release.a ../../bin/libBullet3Collision_gmake_x64_release.a ../../bin/libBullet3Geometry_gmake_x64_release.a -framework OpenGL -framework Cocoa
  LDDEPS    += ../../bin/libBulletExampleBrowserLib_gmake_x64_release.a ../../bin/libgwen_gmake_x64_release.a ../../bin/libOpenGL_Window_gmake_x64_release.a ../../bin/libBulletSoftBody_gmake_x64_release.a ../../bin/libBulletInverseDynamicsUtils_gmake_x64_release.a ../../bin/libBulletInverseDynamics_gmake_x64_release.a ../../bin/libBulletDynamics_gmake_x64_release.a ../../bin/libBulletCollision_gmake_x64_release.a ../../bin/libLinearMath_gmake_x64_release.a ../../bin/libBussIK_gmake_x64_release.a ../../bin/libBullet3Common_gmake_x64_release.a ../../bin/libBullet3OpenCL_clew_gmake_x64_release.a ../../bin/libBullet3Dynamics_gmake_x64_release.a ../../bin/libBullet3Collision_gmake_x64_release.a ../../bin/libBullet3Geometry_gmake_x64_release.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug/App_BulletExampleBrowser
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/App_BulletExampleBrowser_gmake_x64_debug
  DEFINES   += -D_DEBUG=1 -DB3_USE_CLEW -DINCLUDE_CLOTH_DEMOS
  INCLUDES  += -I../../src/clew -I../../examples/ThirdPartyLibs/glad -I../../examples/ExampleBrowser -I../../src -I../../examples/SharedMemory -I../../examples/ThirdPartyLibs
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -ffast-math -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -m64 -L/usr/lib64
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libBulletExampleBrowserLib_gmake_x64_debug.a ../../bin/libgwen_gmake_x64_debug.a ../../bin/libOpenGL_Window_gmake_x64_debug.a ../../bin/libBulletSoftBody_gmake_x64_debug.a ../../bin/libBulletInverseDynamicsUtils_gmake_x64_debug.a ../../bin/libBulletInverseDynamics_gmake_x64_debug.a ../../bin/libBulletDynamics_gmake_x64_debug.a ../../bin/libBulletCollision_gmake_x64_debug.a ../../bin/libLinearMath_gmake_x64_debug.a ../../bin/libBussIK_gmake_x64_debug.a ../../bin/libBullet3Common_gmake_x64_debug.a ../../bin/libBullet3OpenCL_clew_gmake_x64_debug.a ../../bin/libBullet3Dynamics_gmake_x64_debug.a ../../bin/libBullet3Collision_gmake_x64_debug.a ../../bin/libBullet3Geometry_gmake_x64_debug.a -framework OpenGL -framework Cocoa
  LDDEPS    += ../../bin/libBulletExampleBrowserLib_gmake_x64_debug.a ../../bin/libgwen_gmake_x64_debug.a ../../bin/libOpenGL_Window_gmake_x64_debug.a ../../bin/libBulletSoftBody_gmake_x64_debug.a ../../bin/libBulletInverseDynamicsUtils_gmake_x64_debug.a ../../bin/libBulletInverseDynamics_gmake_x64_debug.a ../../bin/libBulletDynamics_gmake_x64_debug.a ../../bin/libBulletCollision_gmake_x64_debug.a ../../bin/libLinearMath_gmake_x64_debug.a ../../bin/libBussIK_gmake_x64_debug.a ../../bin/libBullet3Common_gmake_x64_debug.a ../../bin/libBullet3OpenCL_clew_gmake_x64_debug.a ../../bin/libBullet3Dynamics_gmake_x64_debug.a ../../bin/libBullet3Collision_gmake_x64_debug.a ../../bin/libBullet3Geometry_gmake_x64_debug.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/clew.o \
	$(OBJDIR)/gl.o \
	$(OBJDIR)/main.o \
	$(OBJDIR)/ExampleEntries.o \
	$(OBJDIR)/InverseKinematicsExample.o \
	$(OBJDIR)/FixJointBoxes.o \
	$(OBJDIR)/BoxStack.o \
	$(OBJDIR)/JointLimit.o \
	$(OBJDIR)/geometry.o \
	$(OBJDIR)/model.o \
	$(OBJDIR)/tgaimage.o \
	$(OBJDIR)/our_gl.o \
	$(OBJDIR)/TinyRenderer.o \
	$(OBJDIR)/IKTrajectoryHelper.o \
	$(OBJDIR)/PhysicsClientC_API.o \
	$(OBJDIR)/PhysicsServerExample.o \
	$(OBJDIR)/PhysicsServerExampleBullet2.o \
	$(OBJDIR)/PhysicsClientExample.o \
	$(OBJDIR)/PhysicsServer.o \
	$(OBJDIR)/PhysicsServerSharedMemory.o \
	$(OBJDIR)/PhysicsClientSharedMemory.o \
	$(OBJDIR)/PhysicsClientSharedMemory_C_API.o \
	$(OBJDIR)/PhysicsClientSharedMemory2.o \
	$(OBJDIR)/PhysicsClientSharedMemory2_C_API.o \
	$(OBJDIR)/SharedMemoryCommandProcessor.o \
	$(OBJDIR)/SharedMemoryInProcessPhysicsC_API.o \
	$(OBJDIR)/GraphicsClientExample.o \
	$(OBJDIR)/GraphicsServerExample.o \
	$(OBJDIR)/RemoteGUIHelper.o \
	$(OBJDIR)/PhysicsClient.o \
	$(OBJDIR)/PosixSharedMemory.o \
	$(OBJDIR)/Win32SharedMemory.o \
	$(OBJDIR)/InProcessMemory.o \
	$(OBJDIR)/PhysicsDirect.o \
	$(OBJDIR)/PhysicsDirectC_API.o \
	$(OBJDIR)/PhysicsLoopBack.o \
	$(OBJDIR)/PhysicsLoopBackC_API.o \
	$(OBJDIR)/PhysicsServerCommandProcessor.o \
	$(OBJDIR)/b3PluginManager.o \
	$(OBJDIR)/collisionFilterPlugin.o \
	$(OBJDIR)/TinyRendererVisualShapeConverter.o \
	$(OBJDIR)/tinyRendererPlugin.o \
	$(OBJDIR)/pdControlPlugin.o \
	$(OBJDIR)/b3RobotSimulatorClientAPI_NoGUI.o \
	$(OBJDIR)/b3RobotSimulatorClientAPI_NoDirect.o \
	$(OBJDIR)/MultiThreadingExample.o \
	$(OBJDIR)/b3PosixThreadSupport.o \
	$(OBJDIR)/b3Win32ThreadSupport.o \
	$(OBJDIR)/b3ThreadSupportInterface.o \
	$(OBJDIR)/InverseDynamicsExample.o \
	$(OBJDIR)/b3RobotSimulatorClientAPI.o \
	$(OBJDIR)/BasicExample.o \
	$(OBJDIR)/Dof6ConstraintTutorial.o \
	$(OBJDIR)/Tutorial.o \
	$(OBJDIR)/CompoundBoxes.o \
	$(OBJDIR)/NewtonsRopeCradle.o \
	$(OBJDIR)/MultipleBoxes.o \
	$(OBJDIR)/InclinedPlane.o \
	$(OBJDIR)/RigidBodyFromObj.o \
	$(OBJDIR)/NewtonsCradle.o \
	$(OBJDIR)/SimpleCloth.o \
	$(OBJDIR)/Chain.o \
	$(OBJDIR)/Bridge.o \
	$(OBJDIR)/MultiPendulum.o \
	$(OBJDIR)/SimpleJoint.o \
	$(OBJDIR)/SimpleBox.o \
	$(OBJDIR)/RobotLoggingUtil.o \
	$(OBJDIR)/NN3DWalkers.o \
	$(OBJDIR)/CollisionTutorialBullet2.o \
	$(OBJDIR)/CollisionSdkC_Api.o \
	$(OBJDIR)/KukaGraspExample.o \
	$(OBJDIR)/GripperGraspExample.o \
	$(OBJDIR)/R2D2GraspExample.o \
	$(OBJDIR)/RealTimeBullet3CollisionSdk.o \
	$(OBJDIR)/Bullet2CollisionSdk.o \
	$(OBJDIR)/BenchmarkDemo.o \
	$(OBJDIR)/MultiThreadedDemo.o \
	$(OBJDIR)/CommonRigidBodyMTBase.o \
	$(OBJDIR)/HeightfieldExample.o \
	$(OBJDIR)/ForkLiftDemo.o \
	$(OBJDIR)/SerializeSetup.o \
	$(OBJDIR)/BspLoader.o \
	$(OBJDIR)/BspConverter.o \
	$(OBJDIR)/ImportBspExample.o \
	$(OBJDIR)/LoadMeshFromObj.o \
	$(OBJDIR)/ImportObjExample.o \
	$(OBJDIR)/Wavefront2GLInstanceGraphicsShape.o \
	$(OBJDIR)/BulletMJCFImporter.o \
	$(OBJDIR)/ImportMJCFSetup.o \
	$(OBJDIR)/MyMultiBodyCreator.o \
	$(OBJDIR)/BulletUrdfImporter.o \
	$(OBJDIR)/UrdfParser.o \
	$(OBJDIR)/ImportURDFSetup.o \
	$(OBJDIR)/urdfStringSplit.o \
	$(OBJDIR)/URDF2Bullet.o \
	$(OBJDIR)/ImportSTLSetup.o \
	$(OBJDIR)/b3ImportMeshUtility.o \
	$(OBJDIR)/LoadMeshFromCollada.o \
	$(OBJDIR)/ImportColladaSetup.o \
	$(OBJDIR)/ImportSDFSetup.o \
	$(OBJDIR)/btMultiBodyWorldImporter.o \
	$(OBJDIR)/btWorldImporter.o \
	$(OBJDIR)/btBulletWorldImporter.o \
	$(OBJDIR)/bFile.o \
	$(OBJDIR)/btBulletFile.o \
	$(OBJDIR)/bChunk.o \
	$(OBJDIR)/bDNA.o \
	$(OBJDIR)/Planar2D.o \
	$(OBJDIR)/RenderInstancingDemo.o \
	$(OBJDIR)/TinyRendererSetup.o \
	$(OBJDIR)/CoordinateSystemDemo.o \
	$(OBJDIR)/TimeSeriesFontData.o \
	$(OBJDIR)/TimeSeriesCanvas.o \
	$(OBJDIR)/TimeSeriesExample.o \
	$(OBJDIR)/DynamicTexturedCubeDemo.o \
	$(OBJDIR)/TinyVRGui.o \
	$(OBJDIR)/RaytracerSetup.o \
	$(OBJDIR)/VoronoiFractureDemo.o \
	$(OBJDIR)/btConvexConvexMprAlgorithm.o \
	$(OBJDIR)/SoftDemo.o \
	$(OBJDIR)/DeformableClothAnchor.o \
	$(OBJDIR)/LargeDeformation.o \
	$(OBJDIR)/DeformableSelfCollision.o \
	$(OBJDIR)/Collide.o \
	$(OBJDIR)/DeformableRigid.o \
	$(OBJDIR)/VolumetricDeformable.o \
	$(OBJDIR)/Pinch.o \
	$(OBJDIR)/ClothFriction.o \
	$(OBJDIR)/SplitImpulse.o \
	$(OBJDIR)/PinchFriction.o \
	$(OBJDIR)/DeformableContact.o \
	$(OBJDIR)/DeformableMultibody.o \
	$(OBJDIR)/GraspDeformable.o \
	$(OBJDIR)/MultibodyClothAnchor.o \
	$(OBJDIR)/RollingFrictionDemo.o \
	$(OBJDIR)/btFractureDynamicsWorld.o \
	$(OBJDIR)/btFractureBody.o \
	$(OBJDIR)/FractureDemo.o \
	$(OBJDIR)/MotorDemo.o \
	$(OBJDIR)/Dof6Spring2Setup.o \
	$(OBJDIR)/ConstraintPhysicsSetup.o \
	$(OBJDIR)/TestHingeTorque.o \
	$(OBJDIR)/ConstraintDemo.o \
	$(OBJDIR)/Hinge2Vehicle.o \
	$(OBJDIR)/RaytestDemo.o \
	$(OBJDIR)/MultiDofDemo.o \
	$(OBJDIR)/SerialChains.o \
	$(OBJDIR)/TestJointTorqueSetup.o \
	$(OBJDIR)/Pendulum.o \
	$(OBJDIR)/MultiBodySoftContact.o \
	$(OBJDIR)/MultiBodyConstraintFeedback.o \
	$(OBJDIR)/InvertedPendulumPDControl.o \
	$(OBJDIR)/KinematicMultiBodyExample.o \
	$(OBJDIR)/RigidBodySoftContact.o \
	$(OBJDIR)/KinematicRigidBodyExample.o \
	$(OBJDIR)/stb_image.o \
	$(OBJDIR)/tiny_obj_loader.o \
	$(OBJDIR)/GyroscopicSetup.o \
	$(OBJDIR)/tinyxml2.o \
	$(OBJDIR)/PairBench.o \
	$(OBJDIR)/GpuConvexScene.o \
	$(OBJDIR)/GpuRigidBodyDemo.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking App_BulletExampleBrowser
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning App_BulletExampleBrowser
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	-$(SILENT) cp $< $(OBJDIR)
else
	$(SILENT) xcopy /D /Y /Q "$(subst /,\,$<)" "$(subst /,\,$(OBJDIR))" 1>nul
endif
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
endif

$(OBJDIR)/clew.o: ../../src/clew/clew.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/gl.o: ../../examples/ThirdPartyLibs/glad/gl.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/main.o: ../../examples/ExampleBrowser/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ExampleEntries.o: ../../examples/ExampleBrowser/ExampleEntries.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/InverseKinematicsExample.o: ../../examples/InverseKinematics/InverseKinematicsExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/FixJointBoxes.o: ../../examples/BulletRobotics/FixJointBoxes.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/BoxStack.o: ../../examples/BulletRobotics/BoxStack.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/JointLimit.o: ../../examples/BulletRobotics/JointLimit.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/geometry.o: ../../examples/TinyRenderer/geometry.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/model.o: ../../examples/TinyRenderer/model.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/tgaimage.o: ../../examples/TinyRenderer/tgaimage.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/our_gl.o: ../../examples/TinyRenderer/our_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/TinyRenderer.o: ../../examples/TinyRenderer/TinyRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/IKTrajectoryHelper.o: ../../examples/SharedMemory/IKTrajectoryHelper.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsClientC_API.o: ../../examples/SharedMemory/PhysicsClientC_API.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsServerExample.o: ../../examples/SharedMemory/PhysicsServerExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsServerExampleBullet2.o: ../../examples/SharedMemory/PhysicsServerExampleBullet2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsClientExample.o: ../../examples/SharedMemory/PhysicsClientExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsServer.o: ../../examples/SharedMemory/PhysicsServer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsServerSharedMemory.o: ../../examples/SharedMemory/PhysicsServerSharedMemory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsClientSharedMemory.o: ../../examples/SharedMemory/PhysicsClientSharedMemory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsClientSharedMemory_C_API.o: ../../examples/SharedMemory/PhysicsClientSharedMemory_C_API.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsClientSharedMemory2.o: ../../examples/SharedMemory/PhysicsClientSharedMemory2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsClientSharedMemory2_C_API.o: ../../examples/SharedMemory/PhysicsClientSharedMemory2_C_API.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/SharedMemoryCommandProcessor.o: ../../examples/SharedMemory/SharedMemoryCommandProcessor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/SharedMemoryInProcessPhysicsC_API.o: ../../examples/SharedMemory/SharedMemoryInProcessPhysicsC_API.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GraphicsClientExample.o: ../../examples/SharedMemory/GraphicsClientExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GraphicsServerExample.o: ../../examples/SharedMemory/GraphicsServerExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/RemoteGUIHelper.o: ../../examples/SharedMemory/RemoteGUIHelper.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsClient.o: ../../examples/SharedMemory/PhysicsClient.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PosixSharedMemory.o: ../../examples/SharedMemory/PosixSharedMemory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Win32SharedMemory.o: ../../examples/SharedMemory/Win32SharedMemory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/InProcessMemory.o: ../../examples/SharedMemory/InProcessMemory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsDirect.o: ../../examples/SharedMemory/PhysicsDirect.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsDirectC_API.o: ../../examples/SharedMemory/PhysicsDirectC_API.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsLoopBack.o: ../../examples/SharedMemory/PhysicsLoopBack.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsLoopBackC_API.o: ../../examples/SharedMemory/PhysicsLoopBackC_API.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PhysicsServerCommandProcessor.o: ../../examples/SharedMemory/PhysicsServerCommandProcessor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3PluginManager.o: ../../examples/SharedMemory/b3PluginManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/collisionFilterPlugin.o: ../../examples/SharedMemory/plugins/collisionFilterPlugin/collisionFilterPlugin.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/TinyRendererVisualShapeConverter.o: ../../examples/SharedMemory/plugins/tinyRendererPlugin/TinyRendererVisualShapeConverter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/tinyRendererPlugin.o: ../../examples/SharedMemory/plugins/tinyRendererPlugin/tinyRendererPlugin.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/pdControlPlugin.o: ../../examples/SharedMemory/plugins/pdControlPlugin/pdControlPlugin.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3RobotSimulatorClientAPI_NoGUI.o: ../../examples/SharedMemory/b3RobotSimulatorClientAPI_NoGUI.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3RobotSimulatorClientAPI_NoDirect.o: ../../examples/SharedMemory/b3RobotSimulatorClientAPI_NoDirect.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/MultiThreadingExample.o: ../../examples/MultiThreading/MultiThreadingExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3PosixThreadSupport.o: ../../examples/MultiThreading/b3PosixThreadSupport.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3Win32ThreadSupport.o: ../../examples/MultiThreading/b3Win32ThreadSupport.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3ThreadSupportInterface.o: ../../examples/MultiThreading/b3ThreadSupportInterface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/InverseDynamicsExample.o: ../../examples/InverseDynamics/InverseDynamicsExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3RobotSimulatorClientAPI.o: ../../examples/RobotSimulator/b3RobotSimulatorClientAPI.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/BasicExample.o: ../../examples/BasicDemo/BasicExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Dof6ConstraintTutorial.o: ../../examples/Tutorial/Dof6ConstraintTutorial.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Tutorial.o: ../../examples/Tutorial/Tutorial.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CompoundBoxes.o: ../../examples/ExtendedTutorials/CompoundBoxes.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/NewtonsRopeCradle.o: ../../examples/ExtendedTutorials/NewtonsRopeCradle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/MultipleBoxes.o: ../../examples/ExtendedTutorials/MultipleBoxes.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/InclinedPlane.o: ../../examples/ExtendedTutorials/InclinedPlane.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/RigidBodyFromObj.o: ../../examples/ExtendedTutorials/RigidBodyFromObj.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/NewtonsCradle.o: ../../examples/ExtendedTutorials/NewtonsCradle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/SimpleCloth.o: ../../examples/ExtendedTutorials/SimpleCloth.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Chain.o: ../../examples/ExtendedTutorials/Chain.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Bridge.o: ../../examples/ExtendedTutorials/Bridge.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/MultiPendulum.o: ../../examples/ExtendedTutorials/MultiPendulum.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/SimpleJoint.o: ../../examples/ExtendedTutorials/SimpleJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/SimpleBox.o: ../../examples/ExtendedTutorials/SimpleBox.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/RobotLoggingUtil.o: ../../examples/Utils/RobotLoggingUtil.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/NN3DWalkers.o: ../../examples/Evolution/NN3DWalkers.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CollisionTutorialBullet2.o: ../../examples/Collision/CollisionTutorialBullet2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CollisionSdkC_Api.o: ../../examples/Collision/CollisionSdkC_Api.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/KukaGraspExample.o: ../../examples/RoboticsLearning/KukaGraspExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GripperGraspExample.o: ../../examples/RoboticsLearning/GripperGraspExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/R2D2GraspExample.o: ../../examples/RoboticsLearning/R2D2GraspExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/RealTimeBullet3CollisionSdk.o: ../../examples/Collision/Internal/RealTimeBullet3CollisionSdk.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Bullet2CollisionSdk.o: ../../examples/Collision/Internal/Bullet2CollisionSdk.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/BenchmarkDemo.o: ../../examples/Benchmarks/BenchmarkDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/MultiThreadedDemo.o: ../../examples/MultiThreadedDemo/MultiThreadedDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CommonRigidBodyMTBase.o: ../../examples/MultiThreadedDemo/CommonRigidBodyMTBase.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/HeightfieldExample.o: ../../examples/Heightfield/HeightfieldExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ForkLiftDemo.o: ../../examples/ForkLift/ForkLiftDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/SerializeSetup.o: ../../examples/Importers/ImportBullet/SerializeSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/BspLoader.o: ../../examples/Importers/ImportBsp/BspLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/BspConverter.o: ../../examples/Importers/ImportBsp/BspConverter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ImportBspExample.o: ../../examples/Importers/ImportBsp/ImportBspExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/LoadMeshFromObj.o: ../../examples/Importers/ImportObjDemo/LoadMeshFromObj.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ImportObjExample.o: ../../examples/Importers/ImportObjDemo/ImportObjExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Wavefront2GLInstanceGraphicsShape.o: ../../examples/Importers/ImportObjDemo/Wavefront2GLInstanceGraphicsShape.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/BulletMJCFImporter.o: ../../examples/Importers/ImportMJCFDemo/BulletMJCFImporter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ImportMJCFSetup.o: ../../examples/Importers/ImportMJCFDemo/ImportMJCFSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/MyMultiBodyCreator.o: ../../examples/Importers/ImportURDFDemo/MyMultiBodyCreator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/BulletUrdfImporter.o: ../../examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/UrdfParser.o: ../../examples/Importers/ImportURDFDemo/UrdfParser.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ImportURDFSetup.o: ../../examples/Importers/ImportURDFDemo/ImportURDFSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/urdfStringSplit.o: ../../examples/Importers/ImportURDFDemo/urdfStringSplit.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/URDF2Bullet.o: ../../examples/Importers/ImportURDFDemo/URDF2Bullet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ImportSTLSetup.o: ../../examples/Importers/ImportSTLDemo/ImportSTLSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3ImportMeshUtility.o: ../../examples/Importers/ImportMeshUtility/b3ImportMeshUtility.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/LoadMeshFromCollada.o: ../../examples/Importers/ImportColladaDemo/LoadMeshFromCollada.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ImportColladaSetup.o: ../../examples/Importers/ImportColladaDemo/ImportColladaSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ImportSDFSetup.o: ../../examples/Importers/ImportSDFDemo/ImportSDFSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/btMultiBodyWorldImporter.o: ../../Extras/Serialize/BulletWorldImporter/btMultiBodyWorldImporter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/btWorldImporter.o: ../../Extras/Serialize/BulletWorldImporter/btWorldImporter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/btBulletWorldImporter.o: ../../Extras/Serialize/BulletWorldImporter/btBulletWorldImporter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/bFile.o: ../../Extras/Serialize/BulletFileLoader/bFile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/btBulletFile.o: ../../Extras/Serialize/BulletFileLoader/btBulletFile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/bChunk.o: ../../Extras/Serialize/BulletFileLoader/bChunk.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/bDNA.o: ../../Extras/Serialize/BulletFileLoader/bDNA.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Planar2D.o: ../../examples/Planar2D/Planar2D.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/RenderInstancingDemo.o: ../../examples/RenderingExamples/RenderInstancingDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/TinyRendererSetup.o: ../../examples/RenderingExamples/TinyRendererSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CoordinateSystemDemo.o: ../../examples/RenderingExamples/CoordinateSystemDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/TimeSeriesFontData.o: ../../examples/RenderingExamples/TimeSeriesFontData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/TimeSeriesCanvas.o: ../../examples/RenderingExamples/TimeSeriesCanvas.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/TimeSeriesExample.o: ../../examples/RenderingExamples/TimeSeriesExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/DynamicTexturedCubeDemo.o: ../../examples/RenderingExamples/DynamicTexturedCubeDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/TinyVRGui.o: ../../examples/RenderingExamples/TinyVRGui.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/RaytracerSetup.o: ../../examples/RenderingExamples/RaytracerSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/VoronoiFractureDemo.o: ../../examples/VoronoiFracture/VoronoiFractureDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/btConvexConvexMprAlgorithm.o: ../../examples/VoronoiFracture/btConvexConvexMprAlgorithm.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/SoftDemo.o: ../../examples/SoftDemo/SoftDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/DeformableClothAnchor.o: ../../examples/DeformableDemo/DeformableClothAnchor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/LargeDeformation.o: ../../examples/DeformableDemo/LargeDeformation.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/DeformableSelfCollision.o: ../../examples/DeformableDemo/DeformableSelfCollision.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Collide.o: ../../examples/DeformableDemo/Collide.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/DeformableRigid.o: ../../examples/DeformableDemo/DeformableRigid.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/VolumetricDeformable.o: ../../examples/DeformableDemo/VolumetricDeformable.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Pinch.o: ../../examples/DeformableDemo/Pinch.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ClothFriction.o: ../../examples/DeformableDemo/ClothFriction.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/SplitImpulse.o: ../../examples/DeformableDemo/SplitImpulse.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PinchFriction.o: ../../examples/DeformableDemo/PinchFriction.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/DeformableContact.o: ../../examples/DeformableDemo/DeformableContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/DeformableMultibody.o: ../../examples/DeformableDemo/DeformableMultibody.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GraspDeformable.o: ../../examples/DeformableDemo/GraspDeformable.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/MultibodyClothAnchor.o: ../../examples/DeformableDemo/MultibodyClothAnchor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/RollingFrictionDemo.o: ../../examples/RollingFrictionDemo/RollingFrictionDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/btFractureDynamicsWorld.o: ../../examples/FractureDemo/btFractureDynamicsWorld.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/btFractureBody.o: ../../examples/FractureDemo/btFractureBody.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/FractureDemo.o: ../../examples/FractureDemo/FractureDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/MotorDemo.o: ../../examples/DynamicControlDemo/MotorDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Dof6Spring2Setup.o: ../../examples/Constraints/Dof6Spring2Setup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ConstraintPhysicsSetup.o: ../../examples/Constraints/ConstraintPhysicsSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/TestHingeTorque.o: ../../examples/Constraints/TestHingeTorque.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ConstraintDemo.o: ../../examples/Constraints/ConstraintDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Hinge2Vehicle.o: ../../examples/Vehicles/Hinge2Vehicle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/RaytestDemo.o: ../../examples/Raycast/RaytestDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/MultiDofDemo.o: ../../examples/MultiBody/MultiDofDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/SerialChains.o: ../../examples/MultiBody/SerialChains.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/TestJointTorqueSetup.o: ../../examples/MultiBody/TestJointTorqueSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Pendulum.o: ../../examples/MultiBody/Pendulum.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/MultiBodySoftContact.o: ../../examples/MultiBody/MultiBodySoftContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/MultiBodyConstraintFeedback.o: ../../examples/MultiBody/MultiBodyConstraintFeedback.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/InvertedPendulumPDControl.o: ../../examples/MultiBody/InvertedPendulumPDControl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/KinematicMultiBodyExample.o: ../../examples/MultiBody/KinematicMultiBodyExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/RigidBodySoftContact.o: ../../examples/RigidBody/RigidBodySoftContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/KinematicRigidBodyExample.o: ../../examples/RigidBody/KinematicRigidBodyExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/stb_image.o: ../../examples/ThirdPartyLibs/stb_image/stb_image.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/tiny_obj_loader.o: ../../examples/ThirdPartyLibs/Wavefront/tiny_obj_loader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GyroscopicSetup.o: ../../examples/GyroscopicDemo/GyroscopicSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/tinyxml2.o: ../../examples/ThirdPartyLibs/tinyxml2/tinyxml2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PairBench.o: ../../examples/OpenCL/broadphase/PairBench.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GpuConvexScene.o: ../../examples/OpenCL/rigidbody/GpuConvexScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GpuRigidBodyDemo.o: ../../examples/OpenCL/rigidbody/GpuRigidBodyDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"

-include $(OBJECTS:%.o=%.d)
