# GNU Make project makefile autogenerated by Premake
ifndef config
  config=release64
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),release64)
  OBJDIR     = obj/x64/Release/Bullet3OpenCL_clew
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/libBullet3OpenCL_clew_gmake_x64_release.a
  DEFINES   += -DB3_USE_CLEW
  INCLUDES  += -I../../src/clew -I../../src/Bullet3OpenCL -I../../src
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -msse2 -ffast-math -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -m64 -L/usr/lib64
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug/Bullet3OpenCL_clew
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/libBullet3OpenCL_clew_gmake_x64_debug.a
  DEFINES   += -D_DEBUG=1 -DB3_USE_CLEW
  INCLUDES  += -I../../src/clew -I../../src/Bullet3OpenCL -I../../src
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -ffast-math -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -m64 -L/usr/lib64
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/clew.o \
	$(OBJDIR)/b3GpuSapBroadphase.o \
	$(OBJDIR)/b3GpuParallelLinearBvhBroadphase.o \
	$(OBJDIR)/b3GpuGridBroadphase.o \
	$(OBJDIR)/b3GpuParallelLinearBvh.o \
	$(OBJDIR)/b3StridingMeshInterface.o \
	$(OBJDIR)/b3ContactCache.o \
	$(OBJDIR)/b3QuantizedBvh.o \
	$(OBJDIR)/b3VoronoiSimplexSolver.o \
	$(OBJDIR)/b3TriangleIndexVertexArray.o \
	$(OBJDIR)/b3OptimizedBvh.o \
	$(OBJDIR)/b3GjkEpa.o \
	$(OBJDIR)/b3ConvexHullContact.o \
	$(OBJDIR)/b3TriangleCallback.o \
	$(OBJDIR)/b3OpenCLUtils.o \
	$(OBJDIR)/b3GpuRaycast.o \
	$(OBJDIR)/b3GpuNarrowPhase.o \
	$(OBJDIR)/b3GpuJacobiContactSolver.o \
	$(OBJDIR)/b3GpuPgsConstraintSolver.o \
	$(OBJDIR)/b3Solver.o \
	$(OBJDIR)/b3GpuRigidBodyPipeline.o \
	$(OBJDIR)/b3GpuPgsContactSolver.o \
	$(OBJDIR)/b3GpuGenericConstraint.o \
	$(OBJDIR)/b3PrefixScanCL.o \
	$(OBJDIR)/b3FillCL.o \
	$(OBJDIR)/b3BoundSearchCL.o \
	$(OBJDIR)/b3RadixSort32CL.o \
	$(OBJDIR)/b3LauncherCL.o \
	$(OBJDIR)/b3PrefixScanFloat4CL.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking Bullet3OpenCL_clew
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Bullet3OpenCL_clew
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	-$(SILENT) cp $< $(OBJDIR)
else
	$(SILENT) xcopy /D /Y /Q "$(subst /,\,$<)" "$(subst /,\,$(OBJDIR))" 1>nul
endif
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
endif

$(OBJDIR)/clew.o: ../../src/clew/clew.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3GpuSapBroadphase.o: ../../src/Bullet3OpenCL/BroadphaseCollision/b3GpuSapBroadphase.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3GpuParallelLinearBvhBroadphase.o: ../../src/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvhBroadphase.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3GpuGridBroadphase.o: ../../src/Bullet3OpenCL/BroadphaseCollision/b3GpuGridBroadphase.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3GpuParallelLinearBvh.o: ../../src/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvh.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3StridingMeshInterface.o: ../../src/Bullet3OpenCL/NarrowphaseCollision/b3StridingMeshInterface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3ContactCache.o: ../../src/Bullet3OpenCL/NarrowphaseCollision/b3ContactCache.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3QuantizedBvh.o: ../../src/Bullet3OpenCL/NarrowphaseCollision/b3QuantizedBvh.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3VoronoiSimplexSolver.o: ../../src/Bullet3OpenCL/NarrowphaseCollision/b3VoronoiSimplexSolver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3TriangleIndexVertexArray.o: ../../src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleIndexVertexArray.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3OptimizedBvh.o: ../../src/Bullet3OpenCL/NarrowphaseCollision/b3OptimizedBvh.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3GjkEpa.o: ../../src/Bullet3OpenCL/NarrowphaseCollision/b3GjkEpa.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3ConvexHullContact.o: ../../src/Bullet3OpenCL/NarrowphaseCollision/b3ConvexHullContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3TriangleCallback.o: ../../src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleCallback.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3OpenCLUtils.o: ../../src/Bullet3OpenCL/Initialize/b3OpenCLUtils.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3GpuRaycast.o: ../../src/Bullet3OpenCL/Raycast/b3GpuRaycast.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3GpuNarrowPhase.o: ../../src/Bullet3OpenCL/RigidBody/b3GpuNarrowPhase.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3GpuJacobiContactSolver.o: ../../src/Bullet3OpenCL/RigidBody/b3GpuJacobiContactSolver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3GpuPgsConstraintSolver.o: ../../src/Bullet3OpenCL/RigidBody/b3GpuPgsConstraintSolver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3Solver.o: ../../src/Bullet3OpenCL/RigidBody/b3Solver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3GpuRigidBodyPipeline.o: ../../src/Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipeline.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3GpuPgsContactSolver.o: ../../src/Bullet3OpenCL/RigidBody/b3GpuPgsContactSolver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3GpuGenericConstraint.o: ../../src/Bullet3OpenCL/RigidBody/b3GpuGenericConstraint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3PrefixScanCL.o: ../../src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanCL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3FillCL.o: ../../src/Bullet3OpenCL/ParallelPrimitives/b3FillCL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3BoundSearchCL.o: ../../src/Bullet3OpenCL/ParallelPrimitives/b3BoundSearchCL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3RadixSort32CL.o: ../../src/Bullet3OpenCL/ParallelPrimitives/b3RadixSort32CL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3LauncherCL.o: ../../src/Bullet3OpenCL/ParallelPrimitives/b3LauncherCL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/b3PrefixScanFloat4CL.o: ../../src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanFloat4CL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"

-include $(OBJECTS:%.o=%.d)
